[2024-05-03T13:39:57.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T13:39:57.409+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.upload_file_geolocation manual__2024-05-03T13:39:42.184579+00:00 [queued]>
[2024-05-03T13:39:57.516+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.upload_file_geolocation manual__2024-05-03T13:39:42.184579+00:00 [queued]>
[2024-05-03T13:39:57.524+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-03T13:39:57.693+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_geolocation> on 2024-05-03 13:39:42.184579+00:00
[2024-05-03T13:39:57.794+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=10297) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T13:39:57.811+0000] {standard_task_runner.py:63} INFO - Started process 10467 to run task
[2024-05-03T13:39:57.813+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'upload_file_geolocation', 'manual__2024-05-03T13:39:42.184579+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp0v6p6uc4']
[2024-05-03T13:39:57.815+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask upload_file_geolocation
[2024-05-03T13:39:57.993+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.upload_file_geolocation manual__2024-05-03T13:39:42.184579+00:00 [running]> on host 0db60b1edb75
[2024-05-03T13:39:59.262+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='upload_file_geolocation' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T13:39:42.184579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T13:39:42.184579+00:00'
[2024-05-03T13:39:59.279+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T13:39:59.342+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-03T13:39:59.357+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-03T13:40:02.197+0000] {gcs.py:557} INFO - File /opt/***/dags/data/olist_geolocation_dataset.csv uploaded to olist_geolocation_dataset.csv in storage-capstone bucket
[2024-05-03T13:40:02.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T13:40:02.268+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=upload_file_geolocation, execution_date=20240503T133942, start_date=20240503T133957, end_date=20240503T134002
[2024-05-03T13:40:02.421+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T13:40:02.568+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T13:40:02.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
