[2024-05-05T15:16:25.994+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T15:16:26.044+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_order_dataset scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T15:16:26.062+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_order_dataset scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T15:16:26.063+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T15:16:26.145+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_order_dataset> on 2024-05-04 00:00:00+00:00
[2024-05-05T15:16:26.204+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_order_dataset', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp0rwqwtp6']
[2024-05-05T15:16:26.221+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask create_order_dataset
[2024-05-05T15:16:26.224+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=388) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T15:16:26.231+0000] {standard_task_runner.py:63} INFO - Started process 501 to run task
[2024-05-05T15:16:26.341+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_order_dataset scheduled__2024-05-04T00:00:00+00:00 [running]> on host de3a7fc34b17
[2024-05-05T15:16:27.053+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_order_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-05T15:16:27.055+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T15:16:27.077+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-05T15:16:27.081+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-05T15:16:27.146+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value order.
[2024-05-05T15:16:27.146+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value project-capstone-422211.
[2024-05-05T15:16:27.147+0000] {bigquery.py:481} INFO - Creating dataset: order in project: project-capstone-422211 
[2024-05-05T15:16:27.593+0000] {bigquery.py:2045} INFO - Dataset order already exists.
[2024-05-05T15:16:27.615+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T15:16:27.622+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_order_dataset, execution_date=20240504T000000, start_date=20240505T151626, end_date=20240505T151627
[2024-05-05T15:16:27.679+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-05T15:16:27.854+0000] {taskinstance.py:3482} INFO - 9 downstream tasks scheduled from follow-on schedule check
[2024-05-05T15:16:27.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
