[2024-05-04T11:40:59.616+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T11:40:59.697+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.upload_file_geolocation_to_capstone scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:40:59.743+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.upload_file_geolocation_to_capstone scheduled__2024-05-03T00:00:00+00:00 [queued]>
[2024-05-04T11:40:59.745+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-04T11:41:03.112+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToGCSOperator): upload_file_geolocation_to_capstone> on 2024-05-03 00:00:00+00:00
[2024-05-04T11:41:03.137+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12414) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T11:41:03.138+0000] {standard_task_runner.py:63} INFO - Started process 12516 to run task
[2024-05-04T11:41:03.143+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'upload_file_geolocation_to_capstone', 'scheduled__2024-05-03T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp2xwiow80']
[2024-05-04T11:41:03.144+0000] {standard_task_runner.py:91} INFO - Job 207: Subtask upload_file_geolocation_to_capstone
[2024-05-04T11:41:03.323+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.upload_file_geolocation_to_capstone scheduled__2024-05-03T00:00:00+00:00 [running]> on host d4c1d9b975b8
[2024-05-04T11:41:04.718+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='upload_file_geolocation_to_capstone' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T00:00:00+00:00'
[2024-05-04T11:41:04.721+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T11:41:04.766+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-04T11:41:04.787+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-04T11:41:05.121+0000] {gcs_to_gcs.py:535} INFO - Executing copy of gs://raw_data_projectcapstone/olist_geolocation_dataset.csv to gs://storage-capstone/olist_geolocation_dataset.csv
[2024-05-04T11:41:05.186+0000] {gcs.py:256} INFO - Total Bytes: 61273883 | Bytes Written: 61273883
[2024-05-04T11:41:05.186+0000] {gcs.py:264} INFO - Object olist_geolocation_dataset.csv in bucket raw_data_projectcapstone rewritten to object olist_geolocation_dataset.csv in bucket storage-capstone
[2024-05-04T11:41:05.187+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T11:41:05.195+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=upload_file_geolocation_to_capstone, execution_date=20240503T000000, start_date=20240504T114059, end_date=20240504T114105
[2024-05-04T11:41:05.231+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-04T11:41:05.266+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-04T11:41:05.276+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
